# Environment
task: hopper
behavior: medium-replay-v2
discount: 0.99
observation_shape: [17,]
action_shape: [6,]
modality: state
device: 'cuda:0'



# Model
world_model:
  hidden_dim: 256
  cls_name: MLPWorldModel
  enc_arch: [256, 256, 256]
  recon_arch: [128]   # if empty, one Linear Layer is applied
  reward_arch: [128]  # if empty, one Linear Layer is applied
  done_arch: [128]    # if empty, one Linear Layer is applied



# 
dyn_encoder:
  dyn_batch_size: 256
  arch: [256, 128]
  cls_name: MLPDynamicsEncoder
  dyn_dim: 32  # final output size